version: 0.2

env:
  variables:
            
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - ./node_modules/.bin/eslint .

  build:
    commands:

  post_build:
    commands:

artifacts:
