version: 0.2
  
phases:
  install:
    commands:
      - sudo apt-get install nodejs
      - sudo npm install npm --global
      - npm install
  pre_build:
    commands:
      - ./node_modules/.bin/eslint .