version: 0.2
  
phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.13.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
      - sudo apt-get update
      - sudo apt-get install -y nodejs
      - sudo ln -s "$(which nodejs)" /usr/bin/node
      - sudo apt-get install -y npm
      - npm install 

  pre_build:
    commands:
      - pwd
      - node --version
      - nodejs --version
      - ./node_modules/.bin/eslint .
      
  build:
    commands:
      - docker-compose build
