version: 0.2
  
phases:
  install:
    commands:
      - curl -L "https://github.com/docker/compose/releases/download/1.13.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
      - sudo apt-get update
      - sudo apt-get install nodejs
      - sudo apt-get install npm
      
  pre_build:
    commands:
      - docker-compose --version
      
  build:
    commands:
      - docker-compose build
